apiVersion: v1
kind: Service
metadata:
  name: {{ include "calcapp.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "calcapp.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
