services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    image: omerbs/calcapp:gradle
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - JAVA_OPTS=-Xms256m -Xmx512m
    restart: unless-stopped

